"""
Django settings for air_play project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] if DEBUG else config("ALLOWED_HOSTS").split(",")

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'rest_framework',
     'rest_framework.authtoken',
     'rest_framework_simplejwt',
    'corsheaders',
    'system_management',
    'media_streaming_management',

]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     # 'corsheaders.middleware.CorsMiddleware',

# ]

ROOT_URLCONF = 'air_play.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'air_play.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        
        

    ),
    'EXPIRY_MINUTES': 30,  # Token will expire after 30 minutes

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'system_management.User'
# X_FRAME_OPTIONS = 'ALLOWALL'
X_FRAME_OPTIONS = 'SAMEORIGIN'




# Session and CSRF Security
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = False  # Change to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'  # Or 'Strict'/'None' based on your use case
CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_USE_SESSIONS = False


CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_ALLOW_ALL = False  # Good for security
# Or for development, you can use:
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",  # If you're running frontend locally
    "http://localhost:3000",
    "https://air-play-africa-kkicvp93k-titus-projects-cdab7abf.vercel.app",
    # "http://52.14.111.23",
  # Your Next.js dev server
    
    
]


# CSRF_TRUSTED_ORIGINS = ['https://6820-102-38-124-42.ngrok-free.app']
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    "145.241.184.69.nip.io"


]


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://145.241.184.69.nip.io"
    "https://air-play-africa-kkicvp93k-titus-projects-cdab7abf.vercel.app",

]
   



CORS_ALLOW_CREDENTIALS = True  # Important for sending cookies cross-domain


# If you need to expose specific headers:
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]

# Tell Django it's behind a trusted proxy (NGINX)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')

# Ensure you're not forcing SSL unless you're using HTTPS via AWS ACM/Load Balancer
SECURE_SSL_REDIRECT = False

#for dhango cross site  settings

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False



# BACKBLAZE
BACK_BLAZE_KEY_ID = config('BACK_BLAZE_KEY_ID')
BACK_BLAZE_KEY_NAME = config('BACK_BLAZE_KEY_NAME')
BACK_BLAZE_BUCKET_NAME = config('BACK_BLAZE_BUCKET_NAME')

BACK_BLAZE_APLLICATION_KEY =config('BACK_BLAZE_APLLICATION_KEY')


GROQ_AI_API_KEY = config('GROQ_AI_API_KEY')
BACK_BLAZE_APLLICATION_KEY =config('BACK_BLAZE_APLLICATION_KEY')

BACK_BLAZE_APLLICATION_KEY =config('BACK_BLAZE_APLLICATION_KEY')
PAYSTACK_BASE_URL = config('PAYSTACK_BASE_URL')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')
FRONTEND_URL = 'http://localhost:3000'  # change for production
