# Generated by Django 5.0.8 on 2025-11-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_streaming_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-upload_date']},
        ),
        migrations.RemoveField(
            model_name='track',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='track',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='track',
            name='merit_score',
        ),
        migrations.AddField(
            model_name='track',
            name='ai_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='ai_genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='ai_mood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='ai_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='track',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='track',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='stream_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist', '-upload_date'], name='media_strea_artist__e7b5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['genre'], name='media_strea_genre_458659_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['status'], name='media_strea_status_968fea_idx'),
        ),
    ]
