# Generated by Django 5.0.8 on 2025-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_streaming_management', '0002_alter_track_options_remove_track_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='merit_score',
            field=models.FloatField(default=0.0),
        ),
    ]
