# Generated by Django 5.0.8 on 2026-01-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_streaming_management', '0003_track_merit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
