# Generated by Django 5.0.8 on 2026-01-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_streaming_management', '0004_artist_is_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
