# Generated by Django 5.0.8 on 2026-06-07 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_streaming_management', '0005_artist_onboarding_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_split_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='split_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TrackContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('feature', 'Featured Artist'), ('producer', 'Producer'), ('writer', 'Writer')], max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='media_streaming_management.track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('track', 'email')},
            },
        ),
    ]
