# Generated by Django 5.0.8 on 2026-06-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_streaming_management', '0006_track_is_split_enabled_track_split_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
