# Generated by Django 5.0.8 on 2026-06-10 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_streaming_management', '0008_remove_tip_tx_hash_artist_balance_tip_artist_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='media_streaming_management.artist')),
            ],
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rands', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credits_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_ref', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BlockchainLog',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='amount',
            new_name='credits_amount',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='paystack_ref',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='status',
        ),
        migrations.AlterField(
            model_name='tip',
            name='artist_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tip',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
