# Generated by Django 5.0.8 on 2026-06-14 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_streaming_management', '0010_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='credittopup',
            old_name='paystack_ref',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='credittopup',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('voucher', 'Voucher'), ('manual', 'Manual')], default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='credittopup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='credittopup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to=settings.AUTH_USER_MODEL),
        ),
    ]
